Repository recurly/recurly-client-php, pull requests merged in 2020-06, with the labels that each got.

#500 Include tier attributes in request body
  Tests/Recurly/Subscription_Test.php
  Tests/fixtures/subscriptions/show-200-QBP.xml
  lib/recurly/tier.php
Labels: V2

#498 Use helper method to safeguard against empty path parameters
  Tests/Recurly/Base_Test.php
  lib/recurly/account.php
  lib/recurly/account_acquisition.php
  lib/recurly/account_balance.php
  lib/recurly/addon.php
  lib/recurly/addon_list.php
  lib/recurly/adjustment.php
  lib/recurly/adjustment_list.php
  lib/recurly/base.php
  lib/recurly/billing_info.php
  lib/recurly/client.php
  lib/recurly/coupon.php
  lib/recurly/credit_payment_list.php
  lib/recurly/export_file.php
  lib/recurly/export_file_list.php
  lib/recurly/gift_card.php
  lib/recurly/invoice.php
  lib/recurly/invoice_list.php
  lib/recurly/item.php
  lib/recurly/measured_unit.php
  lib/recurly/note_list.php
  lib/recurly/plan.php
  lib/recurly/redemption.php
  lib/recurly/redemption_list.php
  lib/recurly/resource.php
  lib/recurly/shipping_address_list.php
  lib/recurly/shipping_method.php
  lib/recurly/subscription.php
  lib/recurly/subscription_list.php
  lib/recurly/transaction.php
  lib/recurly/transaction_list.php
  lib/recurly/unique_coupon_code_list.php
  lib/recurly/usage.php
  lib/recurly/usage_list.php
Labels: V2, bug

#503 default parameter gives error
  lib/recurly/adjustment.php
Labels: bug

#504 Convert DateTime objects to ISO8601 strings
  lib/recurly/base_client.php
  tests/BaseClient_Test.php
Labels: enhancement

#505 BACS support
  Tests/Recurly/Billing_Info_Test.php
  Tests/fixtures/billing_info/show-bacs-200.xml
  lib/recurly/billing_info.php
  lib/recurly/client.php
Labels: V2

#509 Fix HTTP 411 error by including Content-Length header
  lib/recurly/http_adapter.php
Labels: bug

#508 Support items on subscriptions
  Tests/Recurly/Subscription_Test.php
  Tests/fixtures/subscriptions/show-200.xml
  lib/recurly/plan.php
  lib/recurly/subscription_addon.php
Labels: V2

#512 Release 2.12.14
  CHANGELOG.md
  lib/recurly/client.php
Labels: V2
