Repository recurly/recurly-client-php, pull requests merged in 2020-03, with the labels that each got.

#466 Adding and Updating Pager tests
  tests/Pager_Test.php
  tests/mock_client.php
Labels: v3

#467 Updating version to GA 3.0.0
  README.md
  composer.json
  lib/recurly/version.php
Labels: v3

#468 Adding parameter comment and including formatted code
  lib/recurly/pager.php
Labels: v3

#469 Moving statusCode checks
  lib/recurly.php
  lib/recurly/client.php
  lib/recurly/response.php
  lib/recurly/util/http_validations.php
Labels: V2

#470 Prevent overwritten address on new purchase with existing account
  Tests/Recurly/Subscription_Test.php
  lib/recurly/account.php
Labels: V2

#474 Add additional attributes to support item-backed add-ons
  Tests/Recurly/Addon_Test.php
  lib/recurly/addon.php
Labels: V2

#477 Release 2.12.12
  CHANGELOG.md
  lib/recurly/client.php
Labels: V2

#475 Enable gzip compression on HTTP responses
  lib/recurly/base_client.php
  lib/recurly/http_adapter.php
  tests/mock_client.php
Labels: enhancement

#483 Add mandate_reference attribute to BillingInfo
  lib/recurly/billing_info.php
Labels: V2

#485 Merge v2.26 features into v2 branch for release
  Tests/Recurly/Addon_Test.php
  Tests/Recurly/Billing_Info_Test.php
  Tests/fixtures/billing_info/show-sepa-200.xml
  lib/recurly/addon.php
  lib/recurly/base.php
  lib/recurly/billing_info.php
  lib/recurly/client.php
  lib/recurly/tier.php
Labels: V2

#486 Release 2.12.13
  CHANGELOG.md
  lib/recurly/client.php
Labels: V2
