Repository recurly/recurly-client-php, pull requests merged in 2020-10, with the labels that each got.

#555 Updating client to be compliant with RFC 2616: case-insensitive headers
  .travis.yml
  CHANGELOG.md
  Tests/Recurly/Pager_Test.php
  Tests/bootstrap.php
  lib/recurly/client.php
  lib/recurly/coupon.php
  lib/recurly/pager.php
  lib/recurly/response.php
Labels: V2, bug

#554 Updating client to be compliant with RFC 2616: case-insensitive headers
  .travis.yml
  CHANGELOG.md
  Tests/Recurly/Pager_Test.php
  Tests/bootstrap.php
  lib/recurly/client.php
  lib/recurly/coupon.php
  lib/recurly/pager.php
  lib/recurly/response.php
Labels: V2, bug

#549 Updating client to be compliant with RFC 2616: case-insensitive headers
  .travis.yml
  CHANGELOG.md
  Tests/test_helpers.php
  lib/recurly/client.php
  lib/recurly/pager.php
Labels: V2, bug

#548 Updating client to be compliant with RFC 2616: case-insensitive headers
  .travis.yml
  CHANGELOG.md
  Tests/test_helpers.php
  lib/recurly/client.php
  lib/recurly/pager.php
Labels: V2, bug

#553 Updating client to be compliant with RFC 2616: case-insensitive headers
  .travis.yml
  CHANGELOG.md
  Tests/bootstrap.php
  lib/recurly/client.php
  lib/recurly/coupon.php
  lib/recurly/pager.php
  lib/recurly/response.php
Labels: V2, bug

#550 Updating client to be compliant with RFC 2616: case-insensitive headers
  .travis.yml
  CHANGELOG.md
  Tests/test_helpers.php
  lib/recurly/client.php
  lib/recurly/pager.php
Labels: V2, bug

#552 Updating client to be compliant with RFC 2616: case-insensitive headers
  .travis.yml
  CHANGELOG.md
  Tests/bootstrap.php
  lib/recurly/client.php
  lib/recurly/coupon.php
  lib/recurly/pager.php
  lib/recurly/response.php
Labels: V2, bug

#551 Updating client to be compliant with RFC 2616: case-insensitive headers
  .travis.yml
  CHANGELOG.md
  Tests/bootstrap.php
  lib/recurly/client.php
  lib/recurly/coupon.php
  lib/recurly/pager.php
Labels: V2, bug

#547 Updating client to be compliant with RFC 2616: case-insensitive headers
  CHANGELOG.md
  lib/recurly/client.php
  lib/recurly/pager.php
  test/fixtures/transactions/show-200-error.xml
  test/recurly/recurlyjs_test.php
  test/test_helpers.php
Labels: V2, bug

#556 Updating client to be compliant with RFC 2616: case-insensitive headers
  .travis.yml
  CHANGELOG.md
  Tests/bootstrap.php
  lib/recurly/client.php
  lib/recurly/coupon.php
  lib/recurly/pager.php
  lib/recurly/response.php
Labels: V2, bug

#506 Adding \Recurly\Logger class and the ability to configure a logger
  README.md
  lib/recurly/base_client.php
  lib/recurly/logger.php
  lib/recurly/response.php
  phpunit.xml.dist
  tests/BaseClient_Test.php
  tests/Logger_Test.php
  tests/Pager_Test.php
  tests/mock_client.php
Labels: enhancement

#559 Mon Oct 19 20:43:37 UTC 2020 Upgrade API version v2019-10-10
  lib/recurly/client.php
  openapi/api.yaml
Labels: enhancement

#561 Implement Pager#take
  lib/recurly/page.php
  lib/recurly/pager.php
  tests/Pager_Test.php
Labels: enhancement, new feature
