Repository recurly/recurly-client-php, pull requests merged in 2020-08, with the labels that each got.

#531 Release 2.12.16
  CHANGELOG.md
  lib/recurly/billing_info.php
  lib/recurly/client.php
Labels: V2

#535 Mon Aug 31 19:51:28 UTC 2020 Upgrade API version v2019-10-10
  lib/recurly/resources/subscription_change.php
  lib/recurly/resources/subscription_change_preview.php
  openapi/api.yaml
Labels: enhancement

#534 Code of Conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation
