Repository recurly/recurly-client-php, pull requests merged in 2020-09, with the labels that each got.

#537 Latest Changes for 2019-10-10 (Automated Exports, additional resource data methods)
  lib/recurly/client.php
  lib/recurly/resources/coupon.php
  lib/recurly/resources/export_dates.php
  lib/recurly/resources/export_file.php
  lib/recurly/resources/export_files.php
  lib/recurly/resources/unique_coupon_code.php
  lib/recurly/resources/usage.php
  openapi/api.yaml
Labels: enhancement

#538 New endpoint to verify an account's billing information
  Tests/Recurly/Billing_Info_Test.php
  Tests/fixtures/billing_info/verify-200.xml
  Tests/fixtures/billing_info/verify-422.xml
  lib/recurly/billing_info.php
Labels: V2

#540 Release 2.12.17
  CHANGELOG.md
  Tests/Recurly/Billing_Info_Test.php
  Tests/fixtures/billing_info/verify-200.xml
  Tests/fixtures/billing_info/verify-422.xml
  lib/recurly/billing_info.php
  lib/recurly/client.php
Labels: V2

#539 Fixing casting for list types that are not in pagers
  lib/recurly/recurly_resource.php
  tests/RecurlyResource_Test.php
Labels: bug

#541 Latest Changes for 2019-10-10
  lib/recurly/resources/coupon.php
  lib/recurly/resources/export_dates.php
  lib/recurly/resources/export_files.php
  openapi/api.yaml
Labels: enhancement

#543 Adding \Recurly\Request to \Recurly\Response
  README.md
  lib/recurly/base_client.php
  lib/recurly/http_adapter.php
  lib/recurly/request.php
  lib/recurly/response.php
  tests/BaseClient_Test.php
  tests/Pager_Test.php
  tests/RecurlyError_Test.php
  tests/RecurlyResource_Test.php
  tests/Request_Test.php
  tests/Response_Test.php
Labels: enhancement

#545 Updating to be compliant with RFC 2616
  lib/recurly/response.php
Labels: bug
