Repository recurly/recurly-client-php, pull requests merged in 2020-11, with the labels that each got.

#565 Release 2.12.18
  CHANGELOG.md
  lib/recurly/client.php
Labels: V2

#564 Latest Changes for 2019-10-10 (Wallet, Item Coupons)
  composer.json
  lib/recurly/client.php
  lib/recurly/errors/service_not_available.php
  lib/recurly/resources/billing_info.php
  lib/recurly/resources/coupon.php
  lib/recurly/resources/invoice.php
  lib/recurly/resources/subscription.php
  openapi/api.yaml
Labels: enhancement

#567 Augment and patch iban implementation
  Tests/Recurly/Billing_Info_Test.php
  Tests/fixtures/billing_info/show-sepa-200.xml
  lib/recurly/billing_info.php
Labels: V2

#562 Implement Pager#take
  Tests/Recurly/Account_List_Test.php
  Tests/Recurly/Invoice_List_Test.php
  Tests/Recurly/ShippingAddress_Test.php
  Tests/fixtures/accounts/index-200-take.xml
  Tests/fixtures/invoices/index-200-take.xml
  Tests/fixtures/shipping_addresses/index-200-take.xml
  lib/recurly/account_list.php
  lib/recurly/coupon_list.php
  lib/recurly/invoice_list.php
  lib/recurly/item_list.php
  lib/recurly/pager.php
  lib/recurly/plan_list.php
  lib/recurly/shipping_address_list.php
  lib/recurly/subscription_list.php
  lib/recurly/transaction_list.php
  lib/recurly/usage_list.php
Labels: V2

#568 Add item_state and external_sku to phpdocs
  lib/recurly/addon.php
Labels: V2

#569 Latest Changes for 2019-10-10
  lib/recurly/client.php
  lib/recurly/resources/subscription.php
  openapi/api.yaml
Labels: enhancement

#571 Update readme to include memo on headers
  README.md
Labels: documentation, v3

#570 Update readme to include headers memo
  README.md
Labels: V2, documentation

#572 Release 2.12.19
  CHANGELOG.md
  lib/recurly/client.php
Labels: V2
