Repository recurly/recurly-client-php, pull requests merged in 2021-08, with the labels that each got.

#621 Fixing issue with http_build_query converting booleans in params to integers
  lib/recurly/base_client.php
  tests/BaseClient_Test.php
Labels: bug, v4

#628 Generated Latest Changes for v2021-02-25
  openapi/api.yaml
Labels: v4

#626 Generated Latest Changes for v2019-10-10
  openapi/api.yaml
Labels: v3

#629 Generated Latest Changes for v2019-10-10 (get_preview_renewal)
  lib/recurly/client.php
  openapi/api.yaml
Labels: v3

#630 Generated Latest Changes for v2021-02-25 (get_preview_renewal)
  lib/recurly/client.php
  openapi/api.yaml
Labels: v4
