Repository recurly/recurly-client-php, pull requests merged in 2021-04, with the labels that each got.

#599 Generated Latest Changes for v2021-02-25
  openapi/api.yaml
Labels: v4

#600 Updating release scripts
  .changelog_config.yaml
  .github_changelog_generator
  scripts/bump
  scripts/changelog
  scripts/prepare-release
  scripts/release
Labels: internal, v4

#601 Updating release scripts
  .changelog_config.yaml
  .github_changelog_generator
  scripts/bump
  scripts/changelog
  scripts/prepare-release
  scripts/release
Labels: internal, v3

#602 Adding release scripts
  .bumpversion.cfg
  .changelog_config.yaml
  scripts/prepare-release
  scripts/release
Labels: V2, internal

#603 Generated Latest Changes for v2021-02-25 (Backup Payment Method)
  lib/recurly/resources/billing_info.php
  lib/recurly/resources/transaction.php
  openapi/api.yaml
Labels: v4

#605 Adding github action workflow to publish docs
  .github/workflows/docs.yml
  scripts/build
  scripts/docs
Labels: internal, v4

#604 Wallet and Backup Payment
  Tests/Recurly/Billing_Info_Test.php
  Tests/fixtures/billing_info/show-200-wallet.xml
  Tests/fixtures/billing_info/show-200.xml
  lib/recurly/account.php
  lib/recurly/base.php
  lib/recurly/billing_info.php
  lib/recurly/billing_info_list.php
  lib/recurly/client.php
  lib/recurly/invoice.php
  lib/recurly/purchase.php
  lib/recurly/subscription.php
Labels: V2

#606 Generated Latest Changes for v2021-02-25
  lib/recurly/resources/subscription_add_on_tier.php
  openapi/api.yaml
Labels: v4

#609 Fixing composer reference in README
  README.md
Labels: internal, v4
