Repository recurly/recurly-client-php, pull requests merged in 2022-04, with the labels that each got.

#678 Generated Latest Changes for v2019-10-10
  lib/recurly/resources/subscription.php
  openapi/api.yaml
Labels: v3

#679 Generated Latest Changes for v2021-02-25
  lib/recurly/resources/add_on.php
  lib/recurly/resources/subscription.php
  lib/recurly/resources/subscription_add_on.php
  openapi/api.yaml
Labels: v4

#682 Setting up github actions
  .github/workflows/ci.yml
  .travis.yml
Labels: v4, internal

#683 3.x actions
  .github/workflows/ci.yml
  .travis.yml
Labels: v3, internal

#685 Updated ci.yml to not reference any java nonsense, this is PHP
  .github/workflows/ci.yml
Labels: v4, internal

#686 Updated ci.yml to not reference any java nonsense, this is PHP
  .github/workflows/ci.yml
Labels: v3, internal

#687 Added ci.yml for github workflows instead of travis ci
  .github/workflows/ci.yml
  .travis.yml
Labels: V2, internal

#690 [API V2] Client Library and Doc Update - PHP
  lib/recurly/base.php
  lib/recurly/measured_unit.php
Labels: V2
