Repository recurly/recurly-client-php, pull requests merged in 2022-09, with the labels that each got.

#711 Fixes method_exists exception on xml_doc.php
  lib/recurly/traits/xml_doc.php
Labels: V2

#713 Generated Latest Changes for v2021-02-25
  lib/recurly/client.php
  lib/recurly/resources/plan_ramp_interval.php
  lib/recurly/resources/subscription_ramp_interval_response.php
  openapi/api.yaml
Labels: v4

#714 Generated Latest Changes for v2021-02-25
  lib/recurly/resources/subscription_ramp_interval_response.php
  openapi/api.yaml
Labels: v4

#715 Add UTF-8 encoding to the DomDocument
  Tests/Recurly/Account_Test.php
  Tests/Recurly/Adjustment_Test.php
  Tests/Recurly/Billing_Info_Test.php
  Tests/Recurly/Coupon_Test.php
  Tests/Recurly/Currency_List_Test.php
  Tests/Recurly/Currency_Percentage_Tier_Test.php
  Tests/Recurly/CustomFieldList_Test.php
  Tests/Recurly/Invoice_Test.php
  Tests/Recurly/Item_Test.php
  Tests/Recurly/Percentage_Tier_Test.php
  Tests/Recurly/Plan_Test.php
  Tests/Recurly/Purchase_Test.php
  Tests/Recurly/Resource_Test.php
  Tests/Recurly/ShippingAddress_Test.php
  lib/recurly/util/xml_tools.php
Labels: bug, V2

#717 Fixing bug with setValues method
  lib/recurly/traits/xml_doc.php
Labels: bug, V2
