Repository recurly/recurly-client-php, pull requests merged in 2022-08, with the labels that each got.

#703 Add Ramp Pricing Feature to Subscriptions
  Tests/Recurly/Plan_Test.php
  Tests/Recurly/Subscription_Test.php
  Tests/bootstrap.php
  Tests/fixtures/plans/show-ramps-200.xml
  Tests/fixtures/subscriptions/index-200.xml
  Tests/fixtures/subscriptions/show-200-ramp-intervals.xml
  lib/recurly.php
  lib/recurly/plan_ramp_interval.php
  lib/recurly/ramp_interval.php
  lib/recurly/subscription.php
  lib/recurly/subscription_ramp_interval.php
  lib/recurly/traits/xml_doc.php
  lib/recurly/util/xml_tools.php
Labels: new feature, V2

#706 Fixes bug with putDunningCampaignBulkUpdate
  lib/recurly/client.php
  openapi/api.yaml
Labels: bug, v4

#709 change method call
  lib/recurly/billing_info.php
Labels: V2
