Repository recurly/recurly-client-php, pull requests merged in 2022-11, with the labels that each got.

#727 Generated Latest Changes for v2019-10-10
  lib/recurly/client.php
  lib/recurly/resources/plan.php
  openapi/api.yaml
Labels: v3

#728 Generated Latest Changes for v2021-02-25
  lib/recurly/client.php
  lib/recurly/resources/add_on.php
  lib/recurly/resources/plan.php
  lib/recurly/resources/subscription_add_on.php
  lib/recurly/resources/usage.php
  openapi/api.yaml
Labels: v4

#729 Generated Latest Changes for v2021-02-25 (External Subscriptions feature)
  lib/recurly/client.php
  lib/recurly/resources/add_on.php
  lib/recurly/resources/external_product.php
  lib/recurly/resources/external_product_reference_mini.php
  lib/recurly/resources/external_resource_mini.php
  lib/recurly/resources/external_subscription.php
  lib/recurly/resources/subscription_add_on.php
  openapi/api.yaml
Labels: v4

#730 v2 updates for external subscriptions and products
  Tests/Recurly/ExternalProduct_List_Test.php
  Tests/Recurly/ExternalProduct_Test.php
  Tests/Recurly/ExternalSubscription_List_Test.php
  Tests/Recurly/ExternalSubscription_Test.php
  Tests/fixtures/external_products/index-200.xml
  Tests/fixtures/external_products/show-200.xml
  Tests/fixtures/external_subscriptions/index-200.xml
  Tests/fixtures/external_subscriptions/show-200.xml
  lib/recurly.php
  lib/recurly/client.php
  lib/recurly/external_product.php
  lib/recurly/external_product_list.php
  lib/recurly/external_product_reference.php
  lib/recurly/external_resource.php
  lib/recurly/external_subscription.php
  lib/recurly/external_subscription_list.php
  lib/recurly/util/xml_tools.php
Labels: V2

#731 Generated Latest Changes for v2019-10-10 (Apply Credit Balance feature)
  lib/recurly/client.php
  lib/recurly/resources/account_balance_amount.php
  openapi/api.yaml
Labels: v3

#732 Generated Latest Changes for v2021-02-25 (Apply Credit Balance feature)
  lib/recurly/client.php
  lib/recurly/resources/account_balance_amount.php
  openapi/api.yaml
Labels: v4

#733 V2 add support for Apply Credit Balance to existing invoice feature
  Tests/Recurly/AccountBalance_Test.php
  Tests/Recurly/Invoice_Test.php
  Tests/fixtures/balance/show-200.xml
  Tests/fixtures/invoices/apply_credit_balance-200.xml
  lib/recurly/account_balance.php
  lib/recurly/invoice.php
  lib/recurly/util/xml_tools.php
Labels: V2
