Repository recurly/recurly-client-php, pull requests merged in 2022-10, with the labels that each got.

#721 Generated Latest Changes for v2019-10-10(Decimal Usage and Quantities)
  lib/recurly/client.php
  lib/recurly/resources/line_item.php
  lib/recurly/resources/plan_ramp_interval.php
  lib/recurly/resources/subscription_ramp_interval_response.php
  lib/recurly/resources/usage.php
  openapi/api.yaml
Labels: v3

#722 Generated Latest Changes for v2021-02-25(Decimal Usage and Quantities and DunningEvent new fields)
  lib/recurly/resources/invoice.php
  lib/recurly/resources/line_item.php
  lib/recurly/resources/usage.php
  openapi/api.yaml
Labels: v4

#725 Generated Latest Changes for v2021-02-25 (Entitlements feature)
  lib/recurly/client.php
  lib/recurly/resources/customer_permission.php
  lib/recurly/resources/entitlement.php
  lib/recurly/resources/entitlements.php
  lib/recurly/resources/granted_by.php
  openapi/api.yaml
Labels: v4

#719 Client lib updates for v2 entitlements
  Tests/Recurly/Account_Test.php
  Tests/Recurly/Entitlement_List_Test.php
  Tests/fixtures/accounts/entitlements/index-200.xml
  Tests/fixtures/accounts/show-200.xml
  lib/recurly.php
  lib/recurly/account.php
  lib/recurly/client.php
  lib/recurly/customer_permission.php
  lib/recurly/entitlement.php
  lib/recurly/entitlement_list.php
  lib/recurly/external_subscription.php
  lib/recurly/util/xml_tools.php
Labels: new feature, V2
