Repository recurly/recurly-client-php, pull requests merged in 2022-02, with the labels that each got.

#658 Adding link to github pages reference docs to the README
  README.md
Labels: v4, internal

#660 Add online_banking_payment_type to billing_info
  Tests/Recurly/Billing_Info_Test.php
  Tests/Recurly/Purchase_Test.php
  lib/recurly/billing_info.php
Labels: new feature, V2

#662 Adding allow-plugins section to composer.json
  composer.json
Labels: v3, internal

#661 Adding allow-plugins section to composer.json
  composer.json
Labels: v4, internal

#663 Generated Latest Changes for v2019-10-10
  lib/recurly/resources/account.php
  lib/recurly/resources/account_mini.php
  lib/recurly/resources/invoice.php
  lib/recurly/resources/plan.php
  openapi/api.yaml
Labels: v3
