Repository recurly/recurly-client-php, pull requests merged in 2024-05, with the labels that each got.

#809 Added support for `proration_settings` for updating subscriptions
  Tests/Recurly/Subscription_Test.php
  lib/recurly.php
  lib/recurly/proration_settings.php
  lib/recurly/subscription.php
  lib/recurly/util/xml_tools.php
Labels: V2

#810 Generated Latest Changes for v2021-02-25 (Proration Settings)
  openapi/api.yaml
Labels: V4

#768 Update params docs for 2021 version
  README.md
Labels: V4, internal

#811 SubscriptionAddon: fix call to undefined method Recurly_SubscriptionAddOn::__valuesString()
  Tests/Recurly/SubscriptionAddOn_Test.php
  lib/recurly/subscription_addon.php
Labels: V2

#812 Generated Latest Changes for v2021-02-25 (Entity Use Code)
  lib/recurly/resources/account.php
  openapi/api.yaml
Labels: V4

#814 Generated Latest Changes for v2021-02-25
  lib/recurly/resources/external_subscription.php
  openapi/api.yaml
Labels: V4
